2022-12-12 14:43:40,799 INFO    StreamThr :191408 [internal.py:wandb_internal():87] W&B internal server running at pid: 191408, started at: 2022-12-12 14:43:40.798562
2022-12-12 14:43:40,802 DEBUG   HandlerThread:191408 [handler.py:handle_request():139] handle_request: status
2022-12-12 14:43:40,805 DEBUG   SenderThread:191408 [sender.py:send_request():317] send_request: status
2022-12-12 14:43:40,807 DEBUG   SenderThread:191408 [sender.py:send():303] send: header
2022-12-12 14:43:40,808 INFO    WriterThread:191408 [datastore.py:open_for_write():75] open: /home/wenxuan/Stable-diffusion-for-book-cover-generation/wandb/run-20221212_144340-2mpkn70q/run-2mpkn70q.wandb
2022-12-12 14:43:40,850 DEBUG   SenderThread:191408 [sender.py:send():303] send: run
2022-12-12 14:43:40,855 INFO    SenderThread:191408 [sender.py:_maybe_setup_resume():593] checking resume status for None/book_cover_generation/2mpkn70q
2022-12-12 14:43:41,851 INFO    WriterThread:191408 [datastore.py:close():279] close: /home/wenxuan/Stable-diffusion-for-book-cover-generation/wandb/run-20221212_144340-2mpkn70q/run-2mpkn70q.wandb
2022-12-12 14:43:41,851 INFO    HandlerThread:191408 [handler.py:finish():814] shutting down handler
2022-12-12 14:43:41,851 ERROR   StreamThr :191408 [internal.py:wandb_internal():162] Thread SenderThread:
Traceback (most recent call last):
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 309, in _process
    self._sm.send(record)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 305, in send
    send_handler(record)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 767, in send_run
    error = self._maybe_setup_resume(run)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 626, in _maybe_setup_resume
    history = json.loads(history[-1])
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
