2022-12-12 14:40:46,899 INFO    StreamThr :191260 [internal.py:wandb_internal():87] W&B internal server running at pid: 191260, started at: 2022-12-12 14:40:46.898247
2022-12-12 14:40:46,902 DEBUG   HandlerThread:191260 [handler.py:handle_request():139] handle_request: status
2022-12-12 14:40:46,904 DEBUG   SenderThread:191260 [sender.py:send_request():317] send_request: status
2022-12-12 14:40:46,907 INFO    WriterThread:191260 [datastore.py:open_for_write():75] open: /home/wenxuan/Stable-diffusion-for-book-cover-generation/wandb/run-20221212_144046-338wajmd/run-338wajmd.wandb
2022-12-12 14:40:46,907 DEBUG   SenderThread:191260 [sender.py:send():303] send: header
2022-12-12 14:40:46,941 DEBUG   SenderThread:191260 [sender.py:send():303] send: run
2022-12-12 14:40:46,946 INFO    SenderThread:191260 [sender.py:_maybe_setup_resume():593] checking resume status for None/book_cover_generation/338wajmd
2022-12-12 14:40:47,942 INFO    WriterThread:191260 [datastore.py:close():279] close: /home/wenxuan/Stable-diffusion-for-book-cover-generation/wandb/run-20221212_144046-338wajmd/run-338wajmd.wandb
2022-12-12 14:40:47,942 INFO    HandlerThread:191260 [handler.py:finish():814] shutting down handler
2022-12-12 14:40:47,943 ERROR   StreamThr :191260 [internal.py:wandb_internal():162] Thread SenderThread:
Traceback (most recent call last):
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 309, in _process
    self._sm.send(record)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 305, in send
    send_handler(record)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 767, in send_run
    error = self._maybe_setup_resume(run)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 626, in _maybe_setup_resume
    history = json.loads(history[-1])
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
