2022-12-10 18:28:50,781 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Configure stats pid to 155951
2022-12-10 18:28:50,781 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/.config/wandb/settings
2022-12-10 18:28:50,781 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/settings
2022-12-10 18:28:50,781 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-10 18:28:50,781 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-12-10 18:28:50,781 INFO    MainThread:155951 [wandb_init.py:_log_setup():476] Logging user logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_182850-zw0344ea/logs/debug.log
2022-12-10 18:28:50,781 INFO    MainThread:155951 [wandb_init.py:_log_setup():477] Logging internal logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_182850-zw0344ea/logs/debug-internal.log
2022-12-10 18:28:50,782 INFO    MainThread:155951 [wandb_init.py:init():516] calling init triggers
2022-12-10 18:28:50,782 INFO    MainThread:155951 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-12-10 18:28:50,782 INFO    MainThread:155951 [wandb_init.py:init():569] starting backend
2022-12-10 18:28:50,782 INFO    MainThread:155951 [wandb_init.py:init():573] setting up manager
2022-12-10 18:28:50,783 INFO    MainThread:155951 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-12-10 18:28:50,786 INFO    MainThread:155951 [wandb_init.py:init():580] backend started and connected
2022-12-10 18:28:50,787 INFO    MainThread:155951 [wandb_init.py:init():658] updated telemetry
2022-12-10 18:28:50,798 INFO    MainThread:155951 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-12-10 18:28:50,891 ERROR   MainThread:155951 [wandb_init.py:init():713] encountered error: resume='must' but run (zw0344ea) doesn't exist
2022-12-10 18:29:07,393 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Configure stats pid to 155951
2022-12-10 18:29:07,394 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/.config/wandb/settings
2022-12-10 18:29:07,394 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/settings
2022-12-10 18:29:07,394 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-10 18:29:07,394 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-12-10 18:29:07,394 INFO    MainThread:155951 [wandb_init.py:_log_setup():476] Logging user logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_182907-fbdkp0mg/logs/debug.log
2022-12-10 18:29:07,394 INFO    MainThread:155951 [wandb_init.py:_log_setup():477] Logging internal logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_182907-fbdkp0mg/logs/debug-internal.log
2022-12-10 18:29:07,394 INFO    MainThread:155951 [wandb_init.py:init():516] calling init triggers
2022-12-10 18:29:07,395 INFO    MainThread:155951 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-12-10 18:29:07,395 INFO    MainThread:155951 [wandb_init.py:init():569] starting backend
2022-12-10 18:29:07,395 INFO    MainThread:155951 [wandb_init.py:init():573] setting up manager
2022-12-10 18:29:07,396 INFO    MainThread:155951 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-12-10 18:29:07,397 INFO    MainThread:155951 [wandb_init.py:init():580] backend started and connected
2022-12-10 18:29:07,399 INFO    MainThread:155951 [wandb_init.py:init():658] updated telemetry
2022-12-10 18:29:07,407 INFO    MainThread:155951 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-12-10 18:29:07,493 ERROR   MainThread:155951 [wandb_init.py:init():713] encountered error: resume='must' but run (fbdkp0mg) doesn't exist
2022-12-10 18:29:41,623 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Configure stats pid to 155951
2022-12-10 18:29:41,623 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/.config/wandb/settings
2022-12-10 18:29:41,624 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/settings
2022-12-10 18:29:41,624 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-10 18:29:41,624 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-12-10 18:29:41,624 INFO    MainThread:155951 [wandb_init.py:_log_setup():476] Logging user logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_182941-fbdkp0mg/logs/debug.log
2022-12-10 18:29:41,624 INFO    MainThread:155951 [wandb_init.py:_log_setup():477] Logging internal logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_182941-fbdkp0mg/logs/debug-internal.log
2022-12-10 18:29:41,624 INFO    MainThread:155951 [wandb_init.py:init():516] calling init triggers
2022-12-10 18:29:41,624 INFO    MainThread:155951 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-12-10 18:29:41,624 INFO    MainThread:155951 [wandb_init.py:init():569] starting backend
2022-12-10 18:29:41,624 INFO    MainThread:155951 [wandb_init.py:init():573] setting up manager
2022-12-10 18:29:41,626 INFO    MainThread:155951 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-12-10 18:29:41,626 INFO    MainThread:155951 [wandb_init.py:init():580] backend started and connected
2022-12-10 18:29:41,628 INFO    MainThread:155951 [wandb_init.py:init():658] updated telemetry
2022-12-10 18:29:41,635 INFO    MainThread:155951 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-12-10 18:30:41,652 ERROR   MainThread:155951 [wandb_init.py:init():704] backend process timed out
2022-12-10 18:30:41,652 ERROR   MainThread:155951 [wandb_init.py:init():713] encountered error: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-12-10 18:31:20,140 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Configure stats pid to 155951
2022-12-10 18:31:20,140 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/.config/wandb/settings
2022-12-10 18:31:20,140 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/settings
2022-12-10 18:31:20,140 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-10 18:31:20,140 INFO    MainThread:155951 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-12-10 18:31:20,140 INFO    MainThread:155951 [wandb_init.py:_log_setup():476] Logging user logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_183120-fbdkp0mg/logs/debug.log
2022-12-10 18:31:20,140 INFO    MainThread:155951 [wandb_init.py:_log_setup():477] Logging internal logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_183120-fbdkp0mg/logs/debug-internal.log
2022-12-10 18:31:20,140 INFO    MainThread:155951 [wandb_init.py:init():516] calling init triggers
2022-12-10 18:31:20,140 INFO    MainThread:155951 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-12-10 18:31:20,141 INFO    MainThread:155951 [wandb_init.py:init():569] starting backend
2022-12-10 18:31:20,141 INFO    MainThread:155951 [wandb_init.py:init():573] setting up manager
2022-12-10 18:31:20,142 INFO    MainThread:155951 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: fork
2022-12-10 18:31:20,143 INFO    MainThread:155951 [wandb_init.py:init():580] backend started and connected
2022-12-10 18:31:20,144 INFO    MainThread:155951 [wandb_init.py:init():658] updated telemetry
2022-12-10 18:31:20,151 INFO    MainThread:155951 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-12-10 18:31:31,211 WARNING MainThread:155951 [wandb_init.py:init():1099] interrupted
Traceback (most recent call last):
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 261, in wait
    found = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 118, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 114, in _wait
    return self._event.wait(timeout=timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2022-12-10 18:31:35,724 WARNING MsgRouterThr:155951 [router.py:message_loop():77] message_loop has been closed
2022-12-10 18:31:35,724 WARNING MsgRouterThr:155951 [router.py:message_loop():77] message_loop has been closed
2022-12-10 18:31:35,725 WARNING MsgRouterThr:155951 [router.py:message_loop():77] message_loop has been closed
2022-12-10 18:31:35,725 WARNING MsgRouterThr:155951 [router.py:message_loop():77] message_loop has been closed
